# 74. Write a python program to create a dictionary with the same keys as the given dictionary and values generated by runnig the given function for each value

dict1 = {'Theodore': {'user': 'Theodore', 'age': 45}, 'Roxanne': {'user': 'Roxanne', 'age': 15}, 'Mathew': {'user': 'Mathew', 'age': 21}}

result = dict(map(lambda x:(x[0], x[1]["age"]),dict1.items()))

print(result)